version: '3.8'

services:
  ranvier:
    build: 
      context: ./ranvier
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ranvier_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - mud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - WS_PORT=8080
      - TELNET_HOST=ranvier
      - TELNET_PORT=3000
    depends_on:
      ranvier:
        condition: service_healthy
    networks:
      - mud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web-client:
    build:
      context: ./web-client
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
    depends_on:
      proxy:
        condition: service_healthy
    networks:
      - mud-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  mud-network:
    driver: bridge

volumes:
  ranvier_data:
    driver: local