global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['monitoring:9100']

  - job_name: 'ranvier-server'
    static_configs:
      - targets: ['ranvier:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'websocket-proxy'
    static_configs:
      - targets: ['proxy:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'web-client'
    static_configs:
      - targets: ['web-client:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    scrape_interval: 30s